version: '3.8'

services:
  dit-manager-frontend:
    build:
      context: .
      dockerfile: ./.docker/Dockerfile.react
    container_name: dit-manager-frontend
    restart: always
    ports:
      - "5173:5173"
    env_file:
      - .env
    volumes:
      - .:/app
      - /app/node_modules
    depends_on:
      - dit-manager-backend
    networks:
      - dit-manager-network

  dit-manager-backend:
    build:
      context: .
      dockerfile: ./.docker/Dockerfile.server
    container_name: dit-manager-backend
    restart: always
    ports:
      - "3001:3001"
    env_file:
      - .env
    networks:
      - dit-manager-network

networks:
  dit-manager-network:
    driver: bridge
